build:
  image: chikim/rails5_skeleton
  environment:
    REPO_URL: git@github.com:framgia/rails5_skeleton.git
    EMAIL_USERNAME: sample@sample.com
    EMAIL_PASSWORD: sample1
    HOST: localhost:3000
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
    S3_BUCKET_NAME: S3_BUCKET_NAME
    DATABASE_HOSTNAME: 127.0.0.1
    DATABASE_NAME: rails_app_development
    DATABASE_USERNAME: test
    DATABASE_PASSWORD: test
    REDIS_HOSTNAME: localhost
    RAILS_ENV: development
    SECRET_KEY_BASE: ci_test
    DEVISE_SECRET_KEY: ci_test
    WEB_SERVER: unicorn
    NUM_UNICORN_WORKERS: 3
commands:
  - sleep 30
  - RAILS_ENV=test rake db:create db:migrate
  - bundle install
  - framgia-ci run

compose:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: rails_app_development
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
cache:
  mount:
    - .git
