#!/usr/bin/env ruby

require "aws-sdk"
client = AWS::ELB.new region: ENV["S3_REGION"],
  access_key_id: ENV["S3_KEY"],
  secret_access_key: ENV["S3_SECRET"]
elb = client.load_balancers.find{|lb| lb.name == ENV["AWS_ELB_NAME"]}
puts elb.instances.map{|i| i.public_ip_address}
